branches:
  only:
    - master
    - stable
language: c++
before_install: echo Preparing installation...
install: echo Installing dependencies...
before_script: echo Preparing building...
script: echo Building...
